# Generated by Django 3.0.8 on 2020-07-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zillow_id', models.CharField(db_index=True, max_length=30)),
                ('link', models.URLField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=3)),
                ('zipcode', models.CharField(max_length=10)),
                ('year_built', models.PositiveSmallIntegerField(null=True)),
                ('home_type', models.CharField(max_length=50)),
                ('home_size', models.PositiveIntegerField(null=True)),
                ('property_size', models.PositiveIntegerField(null=True)),
                ('area_unit', models.CharField(max_length=10)),
                ('bathrooms', models.FloatField(null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(null=True)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_year', models.PositiveSmallIntegerField()),
                ('last_sold_date', models.DateField(null=True)),
                ('last_sold_price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rentzestimate_last_updated', models.DateField(null=True)),
                ('rentzestimate_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('zestimate_last_updated', models.DateField(null=True)),
                ('zestimate_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
